# Generated by Django 4.2.2 on 2023-07-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(blank=True, max_length=7, null=True)),
                ('operation_description', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_cost_h', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ['operation_name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(blank=True, max_length=255, null=True)),
                ('part_drawing_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('part_drawings', models.FileField(blank=True, null=True, upload_to='production/drawings/')),
                ('wood', models.CharField(blank=True, choices=[('OAK', 'ĄŽUOLAS'), ('PINE', 'PUŠIS'), ('BIRCH', 'BERŽAS'), ('BIRCH', 'BERŽAS'), ('FIR', 'EGLĖ'), ('LARCH', 'MAUMEDIS'), ('ASH', 'UOSIS')], max_length=35, null=True)),
                ('wood_type', models.CharField(blank=True, choices=[('DYG', 'DYGIUOTAS'), ('KLJ', 'KLIJUOTAS'), ('MSV', 'MASYVAS')], max_length=35, null=True)),
                ('fsc_status', models.CharField(blank=True, choices=[('FSC 100%', 'FSC 100%'), ('FSC RECYCLED', 'FSC RECYCLED'), ('FSC MIX', 'FSC MIX')], max_length=35, null=True)),
                ('quality_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC')], max_length=35, null=True)),
            ],
            options={
                'ordering': ['code_id'],
            },
        ),
        migrations.CreateModel(
            name='OperationsForPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_time', models.IntegerField(blank=True, default=30, null=True)),
                ('processing_time', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('operation_comment', models.CharField(blank=True, max_length=150, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.operation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.part')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('supplier', models.ManyToManyField(blank=True, to='crm.supplier')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.componenttype')),
            ],
            options={
                'ordering': ['code_id'],
            },
        ),
    ]
