# Generated by Django 4.2.2 on 2023-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_component_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='code_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
