# Generated by Django 4.2.2 on 2023-07-17 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.CharField(blank=True, max_length=11, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('name_spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joining', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('department', models.CharField(blank=True, choices=[('Administracija', 'Administracija'), ('Sandėlys', 'Sandėlys'), ('Kokybės skyrius', 'Kokybės skyrius'), ('Gamybos skyrius', 'Gamybos skyrius')], max_length=35, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='hr/documents/%Y/%m/%d')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id'],
            },
        ),
    ]
