# Generated by Django 4.2.2 on 2023-07-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('production', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_drw_number', models.CharField(max_length=35, null=True, unique=True)),
                ('product_drawings_1', models.FileField(blank=True, null=True, upload_to='production/drawings/')),
                ('product_drawings_2', models.FileField(blank=True, null=True, upload_to='production/drawings/')),
                ('product_drawings_3', models.FileField(blank=True, null=True, upload_to='production/drawings/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.customer')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='PartsForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.part')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='utility.unit')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_time', models.IntegerField(blank=True, default=30, null=True)),
                ('processing_time', models.IntegerField(blank=True, default=1, null=True)),
                ('operation_comment', models.CharField(blank=True, max_length=150, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.operation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.component')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='utility.unit')),
            ],
        ),
    ]
